# Generated by Django 6.0.3 on 2026-04-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Location name', max_length=100)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('priority_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'Critical')], default=2)),
                ('need_name', models.CharField(help_text='What needed', max_length=100)),
                ('need_capacity', models.IntegerField(default=0, help_text='How much needed')),
                ('next_delivery', models.DateTimeField(blank=True, help_text='Next delivery time', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'Critical')], default=2)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(help_text='Products description')),
                ('delivery_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='DeliveryPoint.deliverypoint')),
            ],
        ),
    ]
