# Generated by Django 6.0.3 on 2026-04-05 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeliveryPoint", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypoint",
            name="current_stock_percent",
            field=models.IntegerField(
                default=100, help_text="Current stock percentage (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(default=0, help_text="How much needed"),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("REDIRECTED", "Redirected"),
                    ("FULFILLED", "Fulfilled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="urgency_level",
            field=models.IntegerField(
                choices=[(1, "Low"), (2, "Normal"), (3, "Critical")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="deliverypoint",
            name="need_name",
            field=models.CharField(default="", help_text="What needed", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="content",
            field=models.TextField(default="", help_text="Products description"),
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DISPATCHER", "Dispatcher"),
                            ("OPERATOR", "Operator"),
                            ("MANAGER", "Manager"),
                        ],
                        default="OPERATOR",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="DeliveryPoint.deliverypoint",
                    ),
                ),
            ],
        ),
    ]
