# Generated by Django 6.0.3 on 2026-04-03 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or identifier of a warehouse', max_length=100)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('delivery_radius', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'In stock'), (1, 'Goes to order'), (2, 'Returning')], default=0)),
                ('capacity', models.IntegerField(help_text='Maximum load capacity')),
                ('current_load', models.IntegerField(default=0, help_text='Current weight of goods in the truck')),
                ('current_x', models.IntegerField()),
                ('current_y', models.IntegerField()),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_units', to='Warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of a product', max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('mass', models.IntegerField(help_text='Mass of one unit or total mass')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Warehouse.warehouse')),
            ],
        ),
    ]
